INSERT INTO ROLE(ID, Name) VALUES (1, 'Admin');
INSERT INTO ROLE(ID, Name)
VALUES (2, 'Seller');
INSERT INTO ROLE(ID, Name)
VALUES (3, 'Buyer');
INSERT INTO USER(ID, ADDRESS, NAME, PASSWORD, PHONE, ROLE_ID)
VALUES (1, '1000 N 4th Street, Fairfield, Iowa', 'Win', '12345', '6411111111', 1);
INSERT INTO USER(ID, ADDRESS, NAME, PASSWORD, PHONE, ROLE_ID)
VALUES (2, 'Chicago', 'Welda', '12345', '6412222222', 2);
INSERT INTO USER(ID, ADDRESS, NAME, PASSWORD, PHONE, ROLE_ID)
VALUES (3, 'Myanmar', 'Ei', '12345', '1111111111', 3);
INSERT INTO USER(ID, ADDRESS, NAME, PASSWORD, PHONE, ROLE_ID)
VALUES (4, 'Paris', 'Khaing', '12345', '2222222222', 3);
INSERT INTO CATEGORY(ID, CATEGORY_NAME, DESCRIPTION)
VALUES (1, 'Food', 'Good Food');
INSERT INTO PRODUCT(ID, CATEGORY_ID, DESCRIPTION, IMAGE, NAME, PRICE, SELLER_ID)
VALUES (1, 1, 'This is burmese curry paste', null, 'Tomato paste', 100, 2);
INSERT INTO PRODUCT(ID, CATEGORY_ID, DESCRIPTION, IMAGE, NAME, PRICE, SELLER_ID)
VALUES (2, 1, 'This is american pie crust', null, 'Cocunut crust', 200, 2);
INSERT INTO PRODUCT(ID, CATEGORY_ID, DESCRIPTION, IMAGE, NAME, PRICE, SELLER_ID)
VALUES (3, 1, 'This is egg soup for kids', null, 'Egg Hot', 300, 2);
INSERT INTO CART(ID, USER_ID)
VALUES (1, 3);
INSERT INTO CART_DETAIL(ID, CART_ID, PRODUCT_ID, QUANTITY)
VALUES (1, 1, 1, 10);
INSERT INTO CART_DETAIL(ID, CART_ID, PRODUCT_ID, QUANTITY)
VALUES (2, 1, 2, 20);
INSERT INTO CART_DETAIL(ID, CART_ID, PRODUCT_ID, QUANTITY)
VALUES (3, 1, 3, 30);



